x-app-build: &app-build
  build:
    context: .
    dockerfile: Dockerfile
  image: job-scraper

x-environment: &default-env
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/job_scraper
  CELERY_BROKER_URL: redis://redis:6379/0

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_scraper
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    <<: *app-build
    container_name: job-scraper-api
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      <<: *default-env

  celery_worker:
    <<: *app-build
    container_name: job-scraper-celery-worker
    command: celery -A src.scheduler.app.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      <<: *default-env
    restart: unless-stopped

  celery_beat:
    <<: *app-build
    container_name: job-scraper-celery-beat
    command: celery -A src.scheduler.app.celery beat --loglevel=info
    depends_on:
      - redis
    environment:
      <<: *default-env
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data: